Based on the Movie Plots data( from Friday's class), use topic modeling to group movies in the data set by similarity, as we did in class on Friday (Nov 1). Visualize the results. Can you name the topics?
Experiment with adjustments to the number of topics, number of clusters, and term weightings in the Document Term Matrix to improve your results.
Prepare a document using Quarto that contains the R scripts used in your topic modeling. Include visualizations in your docuement (e.g., cluster plots, scree plots for k, gamma plots, and beta plots) and explain their meaning.   (See the ldatuning package for details about scree plots to help pick k for LDA modeling)

Make an artsy-looking word cloud.

gamma - topics per doc
beta - words per doc
what IS a topic


GROUP MOVIES BY SIMILARITY AKA BY GENRE
going to us k-means, we can use other clutering alglorithms (gausian mixture modelling?)
   k = number of clusters
   you get movie - topic - probability the movie is in that topic
   then you use pivot to put it in one row
we are going 8 genres so 8 clusters for k-means
fviz function to visualize cluster
use csv with genres to see how how many of each genre are in the movie  list


```{r}
library(topicmodels)
library(lexicon)

set.seed(123)
plots <- read.csv("movie_plots.csv")
```

LDA plot
